name: GitHub Secrect Workflow
on:
  push:
jobs:
  github-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetching GitHub Secrect
        run: echo "${{ secrets.GITHUB_TOKEN }}"
